package main

import "fmt"

/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the
 * first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */

func Solution002() string {

	fib_0 := 1
	fib_1 := 2
	answer := 2

	for fib_0 + fib_1 < 4000000 {
		fib_next := fib_0 + fib_1
		fib_0 = fib_1
		fib_1 = fib_next

		if (fib_next % 2 == 0) {
			answer += fib_next
		}
	}

	return fmt.Sprint(answer)
}
